Tammy fisher
TammyLFisher/JavaScript-II pull request #1
Opened 2019-07-01 01:01 UTC by TammyLFisher

2019-07-01 02:14 UTC, dswhitely1 commented on assignments/callbacks.js
> +
Good evening.  I just wanted to show you the solution for this problem.  Can you go and refactor the rest of your answers to match this one.

```sh
function getLength(arr, cb) {
    return cb(arr.length);
}
getLength(items, function(length) {
   console.log(length);
}
```
If you have any further questions, feel free to reach out to your Team Lead or myself during the vacation week.  

Thanks,

Donald Whitely, TL, WEBPT8

2019-07-02 00:06 UTC, liam-mei requested changes

2019-07-02 00:06 UTC, liam-mei commented on assignments/array-methods.js
> +    return nowallCaps.first_name.toUpperCase()});
With JS try to stick to using camel case.  so nowAllCaps would be preferred

2019-07-02 00:06 UTC, Derrick-Mei commented on assignments/callbacks.js
> +      items=>alert(items)
what does this line do? 
`items=>alert(items)`

2019-07-02 00:14 UTC, Derrick-Mei commented
it seems that you're getting the closure and array methods.  Choosing better parameter names might make it a bit more helpful though.

For the callbacks though, you're going to need to work on that.  Donald provided an excellent example and I hope you can refactor the rest of the problems to match it.

For the callbacks/higher order function.  What should be happening is that the higher order function/parent performs some kind of action to a parameter/array in this instance.  Then, returned value is used to invoke the callback function.

What you're doing is that in the higher order function, you're just invoking the callback and not passing it a parameter.  Then you're directly passing the argument into the cb function.

2019-07-08 05:12 UTC, liam-mei approved these changes

2019-07-08 05:12 UTC, Derrick-Mei commented on assignments/callbacks.js
> +  return cb(arr.last);
Here you're using the dot notation on an array.  On arrays, dot notation is to access methods/properties but arrays don't have a `last` property.

items.slice(-1)[0] will return you the last item of the array, but you're doing that on the function invocation and not inside the function declaration.

2019-07-08 05:12 UTC, Derrick-Mei commented on assignments/callbacks.js
> +  return x + y;
Here, you're returning `x + y` but it is not passed into a callback.

2019-07-08 05:12 UTC, Derrick-Mei commented on assignments/callbacks.js
> +  return x * y;
Same here.  You're return the product of x and y but not passing it to the callback.

2019-07-08 05:18 UTC, Derrick-Mei commented
- [x] Array Methods 5/5
- [ ] Callbacks 2/5
- [x] Closures 1/1

--------------
Stretch

- [x] callback
- [ ] closure

-------------

Score: 1

2019-07-08 05:19 UTC, merged